### PR TITLE
Rename sample adapter: AnimalsAdapter and fix it's getItemId()

### LINKED ISSUE #80: Does hasStableIds=true in RecyclerArrayAdapter require a better getItemId() implementation?
[RecyclerArrayAdapter.java](https://github.com/timehop/sticky-headers-recyclerview/blob/516e3798920e61baf93752266ed4c583b6f65428/sample/src/main/java/com/timehop/stickyheadersrecyclerview/sample/RecyclerArrayAdapter.java) you set `setHasStableIds(true)` but then declare

```
public long getItemId(int position) {
    return position;
  }
```

Isn't that a contradiction?

The method `getItemId()` is documented as follows

> Return the stable ID for the item at *position*. If #hasStableIds() would return false this method should return #NO_ID. The default implementation of this method returns #NO_ID
> `@param` position Adapter position to query
> `@return` the stable ID of the item at position

and in `hasStableIds()` we have

> Returns true if this adapter publishes a unique <code>long</code> value that can act as a key for the item at a given position in the data set. **If that item is relocated in the data set, the ID returned for that item should be the same.**
> `@return` true if this adapter's items have stable IDs

I think that as long we don't know a any structure of the elements, it is better to fall back to the default implementation returning `NO_ID`.

### PR DESCRIPTION
**Pull request by webmaster128**
This makes the sample adapter less abstract, which is necessary to provide a correct implementation of getItemId().

Fixes #80

### CODE REVIEW

File: sample/src/main/java/com/timehop/stickyheadersrecyclerview/sample/MainActivity.java [hunk 1]
```diff
@@ -35,7 +34,7 @@ protected void onCreate(Bundle savedInstanceState) {
     final ToggleButton isReverseButton = (ToggleButton) findViewById(R.id.button_is_reverse);
 
     // Set adapter populated with example dummy data
-    final SampleArrayHeadersAdapter mAdapter = new SampleArrayHeadersAdapter();
+    final AnimalsHeadersAdapter mAdapter = new AnimalsHeadersAdapter();
```
Comment (jacobtabak) [inline sample/src/main/java/com/timehop/stickyheadersrecyclerview/sample/MainActivity.java]: I realize you didn't do this but since you're working on this could you please change `mAdapter` to `adapter`? Not sure how that slipped in :)

**Comment by jacobtabak** [comment]
Thanks, nice PR!

File: sample/src/main/java/com/timehop/stickyheadersrecyclerview/sample/MainActivity.java (hunk 1 above)
Comment (webmaster128) [inline sample/src/main/java/com/timehop/stickyheadersrecyclerview/sample/MainActivity.java]: Sure, perfect opportunity to do it now.

**Comment by webmaster128** [comment]
Check.

**Comment by jacobtabak** [comment]
Thanks!
